version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: petzone_db
    environment:
      POSTGRES_USER: petzone
      POSTGRES_PASSWORD: Ruslan280222@
      POSTGRES_DB: petzone_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:

