// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetZone.VolunteerRequests.Infrastructure;

#nullable disable

namespace PetZone.VolunteerRequests.Infrastructure.Migrations
{
    [DbContext(typeof(VolunteerRequestsDbContext))]
    partial class VolunteerRequestsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("volunteer_requests")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetZone.VolunteerRequests.Domain.RejectedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RejectedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("rejected_users", "volunteer_requests");
                });

            modelBuilder.Entity("PetZone.VolunteerRequests.Domain.VolunteerRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiscussionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionComment")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("volunteer_requests", "volunteer_requests");
                });

            modelBuilder.Entity("PetZone.VolunteerRequests.Domain.VolunteerRequest", b =>
                {
                    b.OwnsOne("PetZone.VolunteerRequests.Domain.VolunteerInfo", "VolunteerInfo", b1 =>
                        {
                            b1.Property<Guid>("VolunteerRequestId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<string>("Certificates")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("certificates");

                            b1.Property<int>("Experience")
                                .HasColumnType("integer")
                                .HasColumnName("experience");

                            b1.PrimitiveCollection<string>("Requisites")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("requisites");

                            b1.HasKey("VolunteerRequestId");

                            b1.ToTable("volunteer_requests", "volunteer_requests");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerRequestId");
                        });

                    b.Navigation("VolunteerInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
