POST http://localhost:5183/volunteers
Content-Type: application/json

{
  "firstName": "Иван",
  "lastName": "Иванов",
  "patronymic": "Иванович",
  "email": "ivan@example.com",
  "generalDescription": "Готов помогать",
  "experienceYears": 3,
  "phone": "88005553535",
  "socialNetworks": [],
  "requisites": []
}